-- LISTA DE FILIAIS
SELECT * FROM PCFILIAL 

-- VERIFICAR SE PROMOÇÕES ESTÃO CADASTRADAS CORRETAMENTE
    SELECT 
        f.CODFILIAL ,
        fil.UF ,
        g.CODGRUPOCOMERCIALMED,
        p.CODPROMOCAOMED, 
        p.DATAINICIAL,
        p.DATAFINAL,
        p.IDENTIFICADORPROMOCAO, 
        p.DESCRICAORESUMIDA
    FROM 		PCPROMOCAOMED p 
    INNER JOIN 	PCPROMOCAOGRUPOCOMERCMED	g	ON p.codpromocaomed = g.codpromocaomed 
    INNER JOIN 	PCPROMOCAOFILMED 			f 	ON p.CODPROMOCAOMED = f.CODPROMOCAOMED  
    INNER JOIN  palmed.pcfilial 			fil ON f.CODFILIAL = fil.CODIGO 
    WHERE g.CODGRUPOCOMERCIALMED 
    	IN (9, 10, 11, 12, 13) -- PEDIDO ELETRÔNICO
    AND p.DATAINICIAL = to_Date('2024-02-26', 'yyyy-MM-dd') -- validar a DATA do pedido eletronico
    AND p.IDENTIFICADORPROMOCAO LIKE '%S9T%'-- 
    ORDER BY 1 ASC, 2 ASC, 4 ASC; 
    -- VERIFICAR SE OS GRUPOS ESTÃOS CADASTRADOS
    -- VERIFICAR DATA INICIAL E FINAL DA PROMOÇÃO 
    -- VERIFICAR O IDENTIFICADOR DA PROMOÇÃO