-- ENVIO PROMOÇÃO WHATSAPP TELEVENDAS  (MA, PA, PB, PI)
-- VERIFICAR SE PROMOÇÕES ESTÃO CADASTRADAS CORRETAMENTE
    SELECT 
        f.CODFILIAL ,
        fil.UF ,
        g.CODGRUPOCOMERCIALMED,
        p.CODPROMOCAOMED, 
        p.DATAINICIAL,
        p.DATAFINAL,
        p.IDENTIFICADORPROMOCAO, 
        p.DESCRICAORESUMIDA
    FROM 		PCPROMOCAOMED p 
    INNER JOIN 	PCPROMOCAOGRUPOCOMERCMED	g	ON p.codpromocaomed = g.codpromocaomed 
    INNER JOIN 	PCPROMOCAOFILMED 			f 	ON p.CODPROMOCAOMED = f.CODPROMOCAOMED  
    INNER JOIN  palmed.pcfilial 			fil ON f.CODFILIAL = fil.CODIGO 
    WHERE g.CODGRUPOCOMERCIALMED 
    	IN (4,5,6,7,8,9) -- TELEVENDAS
    AND p.IDENTIFICADORPROMOCAO LIKE '%S9T%' -- S9T: semana 9 televenda 
    ORDER BY 1 ASC, 2 ASC, 4 ASC;
    -- VERIFICAR SE OS GRUPOS ESTÃOS CADASTRADOS
    -- VERIFICAR O IDENTIFICADOR DA PROMOÇÃO







--////////// Para validar as filiais deve ser feito esse select 
-- LISTA DE FILIAIS
SELECT * FROM PCFILIAL 
