NULLIF

SELECT NULLIF(25, 25); 
-- A função NULLIF() compara duas expressões e retorna NULL se forem iguais. Caso contrário, a primeira expressão será retornada.

IS NULL é uma expressão usada para verificar se uma coluna contém um valor nulo.


NULL 
--é um valor especial que indica a ausência de um valor em uma coluna de dados. Ele não é o mesmo que uma string vazia ('') ou um valor numérico zero (0). NULL é usado para representar que o valor é desconhecido ou não aplicável.